### ISSUE TITLE
There may be a problem with the sample code in the documentation

### ISSUE THREAD

**Issue by lythings** [THUMNLab/AutoGL#12]
In documentation _Hyper Parameter Optimization_ [https://autogl.readthedocs.io/en/latest/docfile/tutorial/t_hpo.html#add-your-hpoptimizer](url)
The custom function provided has a 
`loss, self.is_higher_better = current_trainer.get_valid_score(dset)` in function fn
First of all, I think the evaluation index obtained here is not loss, but ACC or AUC， according to the code at  ./solver/classifier/node_classifier.py:

 # fit
        if evaluation_method == "infer":
            if hasattr(dataset, "metric"):
                evaluation_method = [dataset.metric]
            else:
                num_of_label = dataset.num_classes
                if num_of_label == 2:
                    evaluation_method = ["auc"]
                else:
                    evaluation_method = ["acc"]

I think if you don't explicitly specify LogLoss as the evaluation metric in the fit function, it should not be Loss by default.
AND
I'm not sure why there's a parameter **dset** here?  I checked the function ‘get_valid_score’, There is no need to pass in the parameter of dataset. If it's because I didn't look at the code carefully, I got the wrong conclusion. Please point out my mistake, thank you.

**Comment by Frozenmad** [comment]
Sorry for the late response. All members of team are busy preparing recent paper ddl now (until 2021.02.10) and hope you can understand.

Yes you are right, the meaning of returned value here is not `loss` actually but `metric`. We will rename some arguments in the future to reveal its full meanings. However, don't worry about the logic because it is still correct, just improper argument name. 
As you mentioned, the func `get_valid_score()` also return a value named `is_higher_better`. This indicates the polarity of the `metric` returned. For example, if the `metric` is `logloss`, the `is_higher_better` is `False`. If `metric` means `auc`, the `is_higher_better` is `True`.

For the argument passed to `get_valid_score()`. I remember the func should receive no argument. Can you give further explanations about this toturial? @general502570 

We are sorry again for the late response until 2021.02.10 and hope you can understand :)

**Comment by lythings** [comment]
I am very glad to receive your reply,&nbsp;
In the toturial of&nbsp;Add Your HPOptimizer
I think I see a data set passing as an argument to this function.&nbsp;I also found this parameter passing in the original hyperparameter optimization code, such as advisorbase.py and autone.py.
&nbsp;



But I don't think that's probably necessary, is it?





------------------&nbsp;Original&nbsp;------------------

**Comment by Frozenmad** [comment]
Thanks for your reply! Actually I'm asking one of our developers @general502570 who is responsible for HPO part to give further explanation instead of me :). Thanks for your patience and response!

**Comment by general502570** [comment]
Thank you for your question and sorry for my late response. I checked the code and I found you are right. Since `dset` has been passed to `trainer` by func `train`, it is unnecessary to pass it in func `get_valid_score`. We will change the code in the next version.

**Comment by lythings** [comment]
@general502570 Thanks. By the way, in each hyperparameter search method, the definition of search space confuses me in
`space = trainer.hyper_parameter_space + trainer.model.hyper_parameter_space`, 
When the search space is defined this way, I find that there are duplicate terms. I tried to remove `trainer.model.hyper_parameter_space` , so in my code i defined the search space as only `space = trainer.hyper_parameter_spaceand` ,and found that it still works, but I am not sure whether my result will be biased. If you have time, could you please give me the answer

**Comment by Frozenmad** [comment]
:( My fault. Reopening

**Comment by Frozenmad** [comment]
I'm closing this now since this issue is inactive for a long time. If you have further questions, please re-open it or propose a new issue. Thanks!
